services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: mcp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp -d mcp"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./mcp-backend
      dockerfile: Dockerfile
    image: mcp-backend:local
    depends_on:
      mongo:
        condition: service_started
      postgres:
        condition: service_healthy
      toolbox:
        condition: service_started
    environment:
      NODE_ENV: development
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      DATABASE_URL: "postgresql://mcp:mcp@postgres:5432/mcp"
      MCP_TOOLBOX_URL: "http://toolbox:5173/.well-known/mcp/toolbox/sse"
      MCP_SSE_PATH: "/.well-known/mcp/toolbox/sse"
    ports:
      - "3001:3001"
    command:
      ["sh", "-c", "npm run prisma:mongo:push || true; node ./src/app/start.js"]

  ui:
    build:
      context: ./mcp-ui
      dockerfile: Dockerfile
    image: mcp-ui:local
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"

  toolbox:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    hostname: toolbox
    platform: linux/amd64
    ports:
      - "5173:5173"
    volumes:
      - ./config:/config:ro
    command:
      [
        "toolbox",
        "--tools-file",
        "/config/tools.yaml",
        "--address",
        "0.0.0.0",
        "--port",
        "5173",
      ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  mongo-data:
  postgres-data:
